version: '3.6'
services:
  postgres:
    image: postgres:12
    volumes:
    - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hot
      POSTGRES_PASSWORD: hot
      POSTGRES_DATABASE: hot

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./docker-volumes/redis:/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: hot@hot.com
      PGADMIN_DEFAULT_PASSWORD: hot

  hasura:
    image: hasura/graphql-engine:v1.1.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hot:hot@postgres:5432/hot
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsupersecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://sidecar/v1/api/authenticate
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST

  sidecar:
    build: ./sidecar
    ports:
      - "4000:80"
      - "9229:9229"
    environment:
      PORT: 80
      DATABASE_URL: postgres://hot:hot@postgres:5432/hot
    volumes:
      - "./sidecar/:/app"
    command: yarn dev
