version: '3.6'
services:
  postgres:
    image: postgres:12
    volumes:
    - ./docker-volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sos
      POSTGRES_PASSWORD: sos
      POSTGRES_DATABASE: sos

  redis:
    image: redis:alpine
    volumes:
      - ./docker-volumes/redis:/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
    - postgres
    ports:
    - 5050:80
    volumes:
      - "./pgadmin-config.py:/pgadmin4/config_local.py"
      - "./docker-volumes/pgadmin:/var/lib/pgadmin4"
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: sos@sos.com
      PGADMIN_DEFAULT_PASSWORD: sos

  minio:
    image: minio/minio:RELEASE.2020-06-14T18-32-17Z
    volumes:
      - ./docker-volumes/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  hasura:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://sos:sos@postgres:5432/sos
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsupersecretkey

      HASURA_GRAPHQL_AUTH_HOOK: http://sidecar/v1/api/authenticate
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      NEW_USER_WEBHOOK: http://sidecar/v1/api/on-new-user
      NEW_EMPLOYEE_WEBHOOK: http://sidecar/v1/api/on-new-employee
      SIDECAR_GRAPHQL_URL: http://sidecar/v1/graphql

  sidecar:
    build: ./sidecar
    environment:
      PORT: 80
      STORAGE_PORT: 9090
      DATABASE_URL: postgres://sos:sos@postgres:5432/sos
      SOS_ADMIN_EMAILS: "admin@test.com"
    ports:
      - 9090:9090
    volumes:
      - "./sidecar/:/app"
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - hasura
    command: yarn dev

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      CLIENT_GRAPHQL_URL: "http://localhost:8080/v1/graphql"
      SERVER_GRAPHQL_URL: "http://hasura:8080/v1/graphql"
    volumes:
      - ./ui:/app
      - /app/node_modules
    command: yarn dev
