on:
  pull_request:

jobs:
  sanity-check:
    name: UI Sanity Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: yarn install
      run: yarn install
      working-directory: ui

    - name: lint
      run: yarn lint
      working-directory: ui

    - name: typecheck
      run: yarn typecheck
      working-directory: ui
